#!/usr/bin/env python3
"""Replace the vendored OpenAppLock copy catalog with Simplified Chinese."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CATALOGS = [
    ROOT / "OpenAppLockA/Resources/Copy.xcstrings",
    ROOT / "TempMailActivityMonitor/TempMailResources/Copy.xcstrings",
    ROOT / "TempMailShieldConfiguration/Shared/Copy.xcstrings",
    ROOT / "TempMailShieldAction/Shared/Copy.xcstrings",
    ROOT / "TempMailUsageReport/Shared/Copy.xcstrings",
]

TRANSLATIONS = {
    "appLists.appsCountFormat": "%lld 个应用",
    "appLists.appsSectionHeader": "应用",
    "appLists.closeButtonLabel": "关闭",
    "appLists.deleteConfirmationMessage": "此应用列表将被永久删除。",
    "appLists.deleteConfirmationTitle": "删除此列表？",
    "appLists.detailEmptyMessage": "此列表中还没有应用。",
    "appLists.detailReadOnlyFooter": "阻止期间已锁定更改。阻止结束前，此应用列表仅可查看。",
    "appLists.discardChangesAction": "放弃更改",
    "appLists.discardChangesConfirmationTitle": "放弃更改？",
    "appLists.editAppsLabel": "编辑应用",
    "appLists.editListLabel": "编辑列表",
    "appLists.editorNameFieldPlaceholder": "列表名称",
    "appLists.editorNameSectionHeader": "名称",
    "appLists.editorNoAppsYetMessage": "暂未添加应用。",
    "appLists.keepEditingAction": "继续编辑",
    "appLists.libraryDeleteButtonLabel": "删除",
    "appLists.libraryDeletionBlockedAlertMessage": "请先从正在使用此列表的规则中移除它，然后再删除。",
    "appLists.libraryDeletionBlockedAlertTitle": "此列表正在使用中",
    "appLists.libraryEditButtonLabel": "编辑",
    "appLists.libraryEmptyStateDescription": "创建应用列表，以指定规则要作用的应用。",
    "appLists.libraryEmptyStateTitle": "暂无应用列表",
    "appLists.libraryLockedFooter": "规则阻止期间已锁定更改。阻止结束前，现有应用列表仅可查看。",
    "appLists.libraryViewButtonLabel": "查看",
    "appLists.libraryYourAppListsSectionHeader": "我的应用列表",
    "appLists.listActionsLabel": "列表操作",
    "appLists.manageNavigationTitle": "应用列表",
    "appLists.newListLabel": "新建列表",
    "appLists.okButtonLabel": "确定",
    "appLists.oneAppCountLabel": "1 个应用",
    "appLists.saveListAccessibilityLabel": "保存列表",
    "appLists.unsavedEditsMessage": "对此列表的更改尚未保存。",
    "appLists.untitledListDefaultName": "未命名列表",
    "dayPicker.previewSectionHeader": "在这些日期",
    "diagnostics.cancelButton": "取消",
    "diagnostics.clearAllLogsButton": "清除所有日志",
    "diagnostics.clearLogsConfirmationMessage": "此操作将永久删除设备上记录的所有诊断日志。",
    "diagnostics.clearLogsConfirmationTitle": "清除所有日志？",
    "diagnostics.daysSectionFooter": "日志仅保存在本机，不包含具体被阻止应用的信息。",
    "diagnostics.daysSectionHeader": "日期",
    "diagnostics.navigationTitle": "日志",
    "diagnostics.noEntriesPlaceholder": "暂无记录。",
    "diagnostics.noLogsMessage": "暂无日志。规则执行时会自动记录诊断信息。",
    "home.activeRulesSectionHeader": "生效中的规则",
    "home.currentlyBlockingSectionHeader": "当前正在阻止",
    "home.navigationTitle": "首页",
    "home.nothingBlockingMessage": "当前没有正在阻止的内容。",
    "nav.appTitle": "TempMail",
    "nav.homeSectionTitle": "首页",
    "nav.rulesSectionTitle": "规则",
    "nav.settingsSectionTitle": "设置",
    "newRule.closeButton": "关闭",
    "newRule.navigationTitle": "新建规则",
    "newRule.presetSummaryFormat": "%@ · %@",
    "newRule.ruleTypeSectionHeader": "规则类型",
    "notification.timeLimitWarningBodyFormat": "“%@”的使用限额还剩 %lld 分钟。",
    "notification.timeLimitWarningTitle": "使用时长即将用完",
    "notifications.allowButton": "允许通知",
    "notifications.allowedStatusLabel": "已允许通知",
    "notifications.deniedFooter": "TempMail 的通知已关闭。请在系统设置中开启，以接收这些提醒。",
    "notifications.footer": "“计划即将开始”会在计划规则生效前 5 分钟提醒；“使用时长即将用完”会在限额剩余 5 分钟时提醒。",
    "notifications.navigationTitle": "通知",
    "notifications.notifyMeSectionHeader": "提醒我",
    "notifications.openSettingsButton": "打开系统设置",
    "notifications.permissionSectionHeader": "权限",
    "notifications.scheduleStartToggleLabel": "计划即将开始",
    "notifications.timeLimitToggleLabel": "使用时长即将用完",
    "onboarding.accessDeclinedMessage": "屏幕使用时间权限未获允许。没有此权限，TempMail 无法阻止应用。",
    "onboarding.activityStaysPrivateBullet": "你的应用活动仅保留在本机，不会被收集。",
    "onboarding.allowScreenTime": "允许屏幕使用时间权限",
    "onboarding.changeAnytimeBullet": "你可以随时在设置中更改。",
    "onboarding.continueButton": "继续",
    "onboarding.openSettingsButton": "打开系统设置",
    "onboarding.requesting": "正在请求…",
    "onboarding.screenTimeFrameworkBullet": "TempMail 使用 Apple 的屏幕使用时间框架阻止你选择的应用。",
    "onboarding.welcomeDescription": "帮助你减少分心，专注当下。",
    "onboarding.welcomeTitle": "TempMail",
    "preset.balanceSectionSubtitle": "把时间留给真正重要的事情。",
    "preset.balanceSectionTitle": "健康平衡",
    "preset.deepWorkName": "深度工作",
    "preset.eveningResetName": "晚间重置",
    "preset.familyDinnerName": "家庭晚餐",
    "preset.focusSectionSubtitle": "守护你的深度工作时间。",
    "preset.focusSectionTitle": "专注时间",
    "preset.lightsOutName": "准时入睡",
    "preset.morningFocusName": "晨间专注",
    "preset.restSectionSubtitle": "按计划放松身心。",
    "preset.restSectionTitle": "休息充电",
    "preset.screenFreeSundayName": "无屏星期日",
    "ruleDetail.appListSummaryFormat": "%@ · %@",
    "ruleDetail.closeButton": "关闭",
    "ruleDetail.dailyMinutesSummaryFormat": "每天 %lld 分钟",
    "ruleDetail.deleteAction": "删除",
    "ruleDetail.deleteConfirmationMessage": "此规则将被永久删除。",
    "ruleDetail.deleteConfirmationTitle": "删除此规则？",
    "ruleDetail.detailsSectionHeader": "详细信息",
    "ruleDetail.disableAction": "停用",
    "ruleDetail.disableConfirmationMessage": "此规则将保持停用，直到你再次启用。",
    "ruleDetail.disableConfirmationTitleFormat": "停用“%@”？",
    "ruleDetail.discardChangesAction": "放弃更改",
    "ruleDetail.discardChangesTitle": "放弃更改？",
    "ruleDetail.doneLabel": "完成",
    "ruleDetail.duringThisTimeRowLabel": "时间段",
    "ruleDetail.editButton": "编辑",
    "ruleDetail.enableAction": "启用",
    "ruleDetail.forThisLongRowLabel": "使用时长",
    "ruleDetail.generalSectionHeader": "常规",
    "ruleDetail.hardModeLockedNotice": "阻止期间已锁定更改。阻止结束前，此规则仅可查看。",
    "ruleDetail.keepEditingAction": "继续编辑",
    "ruleDetail.kindRowLabel": "类型",
    "ruleDetail.moreThanRowLabel": "打开次数",
    "ruleDetail.noAppsPlaceholder": "未选择应用",
    "ruleDetail.noValue": "否",
    "ruleDetail.onTheseDaysRowLabel": "日期",
    "ruleDetail.opensCountSummaryFormat": "每天 %lld 次",
    "ruleDetail.pauseConfirmationMessage": "此规则将暂停 15 分钟。",
    "ruleDetail.pauseConfirmationTitleFormat": "暂停“%@”？",
    "ruleDetail.pauseFor15MinutesAction": "暂停 15 分钟",
    "ruleDetail.pausingAllowedRowLabel": "允许暂停",
    "ruleDetail.resumeBlockingAction": "恢复阻止",
    "ruleDetail.ruleActionsLabel": "规则操作",
    "ruleDetail.statusRowLabel": "状态",
    "ruleDetail.thenBlockUntilRowLabel": "阻止至",
    "ruleDetail.todaysUsageLabel": "今日使用情况",
    "ruleDetail.tomorrowValue": "明天",
    "ruleDetail.unsavedEditsMessage": "对此规则的更改尚未保存。",
    "ruleDetail.usageReportNavigationTitle": "使用情况",
    "ruleDetail.whenIOpenRowLabel": "应用",
    "ruleDetail.whenIUseRowLabel": "应用",
    "ruleDetail.yesValue": "是",
    "ruleEditor.addRuleLabel": "添加规则",
    "ruleEditor.appListSummaryFormat": "%@ · %@",
    "ruleEditor.appListTitle": "应用列表",
    "ruleEditor.appsAreBlockedHeader": "阻止这些应用",
    "ruleEditor.cantPauseWhileActive": "此规则生效时无法暂停。",
    "ruleEditor.chooseAppListPlaceholder": "选择",
    "ruleEditor.dailyLabel": "每天",
    "ruleEditor.dailyMinutesAbbreviatedFormat": "%lld 分钟",
    "ruleEditor.dailyMinutesAccessibilityFormat": "%lld 分钟",
    "ruleEditor.dailyOpenLimitAccessibilityLabel": "每日打开次数限制",
    "ruleEditor.dailyTimeLimitAccessibilityLabel": "每日使用时长限制",
    "ruleEditor.duringThisTimeHeader": "在此时间段内",
    "ruleEditor.forThisLongHeader": "使用超过",
    "ruleEditor.fromLabel": "开始",
    "ruleEditor.hardModeToggle": "阻止期间锁定更改",
    "ruleEditor.modeLabel": "模式",
    "ruleEditor.moreThanHeader": "超过",
    "ruleEditor.nameSectionHeader": "名称",
    "ruleEditor.onlyTheseAppsAllowedHeader": "仅允许这些应用",
    "ruleEditor.onTheseDaysHeader": "在这些日期",
    "ruleEditor.opensCountFormat": "%lld 次",
    "ruleEditor.ruleNamePlaceholder": "规则名称",
    "ruleEditor.thenBlockAppHeader": "随后阻止应用",
    "ruleEditor.toLabel": "结束",
    "ruleEditor.tomorrowValue": "明天",
    "ruleEditor.untilLabel": "直到",
    "ruleEditor.whenIOpenHeader": "当我打开",
    "ruleEditor.whenIUseHeader": "当我使用",
    "ruleKind.defaultNameOpenLimit": "打开守门员",
    "ruleKind.defaultNameSchedule": "专注时段",
    "ruleKind.defaultNameTimeLimit": "时间守门员",
    "ruleKind.openLimitDisplayName": "打开次数限制",
    "ruleKind.openLimitExampleText": "例如：每天 5 次",
    "ruleKind.scheduleDisplayName": "定时计划",
    "ruleKind.scheduleExampleText": "例如：每天 9:00–17:00",
    "ruleKind.timeLimitDisplayName": "使用时长限制",
    "ruleKind.timeLimitExampleText": "例如：每天 45 分钟",
    "rulesList.emptyStateDescription": "创建规则，按计划阻止容易分心的应用。",
    "rulesList.navigationTitle": "规则",
    "rulesList.newRuleButton": "新建规则",
    "rulesList.noRulesYetTitle": "暂无规则",
    "rulesList.ruleLimitAlertMessage": "最多可创建 %lld 条规则。请删除一条后再添加。",
    "rulesList.ruleLimitAlertTitle": "已达到规则数量上限",
    "screenTimeAccess.description": "没有屏幕使用时间权限，TempMail 无法执行阻止。请在系统设置中重新开启，以确保规则正常工作。",
    "screenTimeAccess.openSettingsButton": "打开系统设置",
    "screenTimeAccess.title": "需要屏幕使用时间权限",
    "selectionMode.allowOnly": "仅允许",
    "selectionMode.block": "阻止",
    "settings.aboutSectionHeader": "关于",
    "settings.appListsRowLabel": "应用列表",
    "settings.githubLinkLabel": "GitHub",
    "settings.logsRowLabel": "日志",
    "settings.moreSettingsSectionHeader": "更多设置",
    "settings.navigationTitle": "设置",
    "settings.notificationsRowLabel": "通知",
    "settings.protectionSectionHeader": "保护",
    "settings.uninstallProtectionLockedFooter": "锁定规则正在阻止时，无法更改此项。",
    "settings.uninstallProtectionToggleLabel": "锁定规则生效时禁止卸载应用",
    "settings.uninstallProtectionUnlockedFooter": "启用“阻止期间锁定更改”的规则生效时，任何应用都无法被删除。",
    "settings.websiteLinkLabel": "官方网站",
    "shield.blockedSubtitle": "此应用已被 TempMail 阻止。",
    "shield.blockedTitle": "应用已阻止",
    "shield.noOpensLeft": "今天的打开次数已用完，阻止将在明天解除。",
    "shield.openButtonMany": "打开（剩余 %lld 次）",
    "shield.openButtonOne": "打开（剩余 1 次）",
    "shield.openLimit.subtitle": "今天已打开 %lld/%lld 次。每次可使用 %lld 分钟。",
    "shield.openLimitJustBlocked.subtitle": "你刚刚使用了一次打开机会，稍后仍可再次打开。",
    "shield.primaryButtonLabel": "确定",
    "status.activeLeft": "%@后结束",
    "status.countdownDays": "%lld天",
    "status.countdownHours": "%lld小时",
    "status.countdownMinutes": "%lld分钟",
    "status.disabled": "已停用",
    "status.noDaysSelected": "未选择日期",
    "status.resetsIn": "%@后重置",
    "status.resumesIn": "%@后恢复",
    "status.startsIn": "%@后开始",
    "usage.subtitleSeparator": "%@ · %@",
    "usageReport.durationHoursFormat": "%lld小时",
    "usageReport.durationHoursMinutesFormat": "%lld小时%lld分钟",
    "usageReport.durationMinutesFormat": "%lld分钟",
    "usageReport.noUsageToday": "今天暂无使用记录",
    "usageReport.todayTotalFormat": "今日共 %@",
    "usageReport.underAMinute": "不足 1 分钟",
    "usageReport.unknownAppName": "未知应用",
    "weekday.everyDaySummary": "每天",
    "weekday.fridayAbbreviation": "周五",
    "weekday.mondayAbbreviation": "周一",
    "weekday.neverSummary": "从不",
    "weekday.saturdayAbbreviation": "周六",
    "weekday.shortLabelF": "五",
    "weekday.shortLabelM": "一",
    "weekday.shortLabelS": "日",
    "weekday.shortLabelT": "二",
    "weekday.shortLabelW": "三",
    "weekday.sundayAbbreviation": "周日",
    "weekday.thursdayAbbreviation": "周四",
    "weekday.tuesdayAbbreviation": "周二",
    "weekday.wednesdayAbbreviation": "周三",
    "weekday.weekdaysSummary": "工作日",
    "weekday.weekendsSummary": "周末",
}


def main() -> None:
    with CATALOGS[0].open(encoding="utf-8") as handle:
        catalog = json.load(handle)

    catalog_keys = set(catalog["strings"])
    translation_keys = set(TRANSLATIONS)
    missing = sorted(catalog_keys - translation_keys)
    extra = sorted(translation_keys - catalog_keys)
    if missing or extra:
        raise SystemExit(f"translation key mismatch; missing={missing}, extra={extra}")

    catalog["sourceLanguage"] = "zh-Hans"
    for key, entry in catalog["strings"].items():
        entry["localizations"] = {
            "zh-Hans": {
                "stringUnit": {
                    "state": "translated",
                    "value": TRANSLATIONS[key],
                }
            }
        }

    rendered = json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"
    for path in CATALOGS:
        path.write_text(rendered, encoding="utf-8")
        print(f"LOCALIZED {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
